# Generated by Django 2.2.10 on 2021-06-30 02:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledCourses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=15, null=True)),
                ('course_category', models.CharField(max_length=15, null=True)),
                ('course_diff', models.CharField(choices=[('e', 'EASY'), ('m', 'MEDIUM'), ('h', 'HARD')], default='e', max_length=1)),
            ],
        ),
    ]
